# Generated by Django 5.0.14 on 2026-01-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0059_nopromotepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadOnlyApprovalTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
                ('groups', models.ManyToManyField(help_text='Users in these groups can approve or reject.', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'read-only approval task',
                'verbose_name_plural': 'read-only approval tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
